### ISSUE TITLE
Cannot lock device after running tests

### ISSUE THREAD

**Issue by mckees** [canonical/checkbox-kivu#58]
The disabling of the screen saver is never undone by the test scripts, which gives my machine pretty intense insomnia. At some point, we should run:

/usr/bin/gsettings set org.gnome.desktop.lockdown disable-lock-screen 'false'

I haven't dug into what else some of these scripts are doing, but it seems like a good idea to do an audit to make sure that system changes are undone after the test is completed.

**Comment by petitfou** [comment]
That is quite complicated to revert all changes made into a system by the test run, both because checkbox does not offer some "teardown" mechanism (as far as i know) and also because it is quite complicated by design, we can however try to do our best to let the system state as close as possible to the state before the test run

**Comment by mckees** [comment]
We can use a second job in an "after", as seen here:
https://github.com/canonical/checkbox/blob/main/providers/base/units/tpm/sysfs.pxu#L57

**Comment by petitfou** [comment]
It is not that easy (not one line of code like that), you will have to duplicate that several times, ... to make sure that this cleanup will be run whereever it is necessary and at the appropriate moment

**Comment by petitfou** [comment]
Generally other test frameworks offer a teardown job for a test or a test suite, this mecanism is the most appropriate for our need but checkbox does not offer this

**Comment by mckees** [comment]
Fixed with #61
